#!/bin/bash -e

function die() {
    echo >&2 ERROR: $*
    exit 1
}

GEANT=$(readlink -f $(dirname "${0}"))/runA2Geant.sh
QSUB="qsub -V -lwalltime=8:00:00 -lncpus=1"

test -x "${GEANT}" || die "A2 Geant not found/not executable: ${GEANT}"

mkdir -p a2geant_out

outpath="$(pwd)/a2geant"

while read file; do
    fullin=$(readlink -f "${file}")
    fullout="${outpath}/geant_$(basename ${file})"
    jobname="Sim_$(basename ${file})"
    echo \"${GEANT}\" \"${fullin}\" \"${fullout}\" | $QSUB -N "${jobname}"
done

