#####Pre-Initialisation
#Choose a physics list, for a full listing type /A2/physics/ListPhysics
/A2/physics/Physics QGSP_BERT_HP

####Initialise
/run/initialize

/A2/generator/Mode 1
/A2/generator/SetTMax 500 MeV
/A2/generator/SetTMin 50 MeV
/A2/generator/SetThetaMin 0 deg
/A2/generator/SetThetaMax 180 deg
/A2/generator/SetBeamXSigma 1 mm
/A2/generator/SetBeamYSigma 1 mm
/A2/generator/SetTargetZ0 0 m
/A2/generator/SetTargetThick 0.1 mm
/A2/generator/SetTargetRadius 0.1 mm

/A2/event/setOutputFile /scratch/Mainz_Software/Data/NeutronBeam_10e6.root

/gun/particle neutron
#/gun/position 0 0 -10 m
#/gun/direction 0 0 1 
#/gun/energy 100 MeV
/run/beamOn 1000000
